# Generated by Django 4.2.6 on 2023-10-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/slider_image/')),
                ('Deals', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels'), ('New DEALS', 'New DEALS')], max_length=100)),
                ('Sale', models.IntegerField()),
                ('Brand_name', models.CharField(max_length=200)),
                ('Discounts', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
