# Generated by Django 4.2.6 on 2023-10-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_slider_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(upload_to='media/banner_image/')),
                ('BannerDeals', models.CharField(max_length=100)),
                ('Quote', models.CharField(max_length=100)),
                ('Discounts', models.IntegerField()),
            ],
        ),
    ]
