# Generated by Django 4.2.6 on 2023-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_brand_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='packing_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
